#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resto.Front.Api.HorecaControlPlugin.Sql
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    public partial class HorecaContext : System.Data.Linq.DataContext
    {
        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void InsertEvents(Events instance);
        partial void UpdateEvents(Events instance);
        partial void DeleteEvents(Events instance);
        partial void InsertHighRiskOperations(HighRiskOperations instance);
        partial void UpdateHighRiskOperations(HighRiskOperations instance);
        partial void DeleteHighRiskOperations(HighRiskOperations instance);
        partial void InsertMessages(Messages instance);
        partial void UpdateMessages(Messages instance);
        partial void DeleteMessages(Messages instance);
        partial void InsertOrders(Orders instance);
        partial void UpdateOrders(Orders instance);
        partial void DeleteOrders(Orders instance);
        partial void InsertShifts(Shifts instance);
        partial void UpdateShifts(Shifts instance);
        partial void DeleteShifts(Shifts instance);
        partial void InsertUsers(Users instance);
        partial void UpdateUsers(Users instance);
        partial void DeleteUsers(Users instance);

        #endregion

        public HorecaContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public HorecaContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public HorecaContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public HorecaContext(System.Data.IDbConnection connection,
            System.Data.Linq.Mapping.MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<Events> Events
        {
            get { return this.GetTable<Events>(); }
        }

        public System.Data.Linq.Table<HighRiskOperations> HighRiskOperations
        {
            get { return this.GetTable<HighRiskOperations>(); }
        }

        public System.Data.Linq.Table<Messages> Messages
        {
            get { return this.GetTable<Messages>(); }
        }

        public System.Data.Linq.Table<Orders> Orders
        {
            get { return this.GetTable<Orders>(); }
        }

        public System.Data.Linq.Table<Shifts> Shifts
        {
            get { return this.GetTable<Shifts>(); }
        }

        public System.Data.Linq.Table<Users> Users
        {
            get { return this.GetTable<Users>(); }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Events : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.Guid _Uuid;

        private System.DateTime _DateTime;

        private System.Data.Linq.Binary _Event;

        private bool _IsSent;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnUuidChanging(System.Guid value);
        partial void OnUuidChanged();
        partial void OnDateTimeChanging(System.DateTime value);
        partial void OnDateTimeChanged();
        partial void OnEventChanging(System.Data.Linq.Binary value);
        partial void OnEventChanged();
        partial void OnIsSentChanging(bool value);
        partial void OnIsSentChanged();

        #endregion

        public Events()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Uuid", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid Uuid
        {
            get { return this._Uuid; }
            set
            {
                if ((this._Uuid != value))
                {
                    this.OnUuidChanging(value);
                    this.SendPropertyChanging();
                    this._Uuid = value;
                    this.SendPropertyChanged("Uuid");
                    this.OnUuidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DateTime", DbType = "DateTime NOT NULL")]
        public System.DateTime DateTime
        {
            get { return this._DateTime; }
            set
            {
                if ((this._DateTime != value))
                {
                    this.OnDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._DateTime = value;
                    this.SendPropertyChanged("DateTime");
                    this.OnDateTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Event", DbType = "Image", CanBeNull = true,
            UpdateCheck = UpdateCheck.Never)]
        public System.Data.Linq.Binary Event
        {
            get { return this._Event; }
            set
            {
                if ((this._Event != value))
                {
                    this.OnEventChanging(value);
                    this.SendPropertyChanging();
                    this._Event = value;
                    this.SendPropertyChanged("Event");
                    this.OnEventChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsSent", DbType = "Bit NOT NULL")]
        public bool IsSent
        {
            get { return this._IsSent; }
            set
            {
                if ((this._IsSent != value))
                {
                    this.OnIsSentChanging(value);
                    this.SendPropertyChanging();
                    this._IsSent = value;
                    this.SendPropertyChanged("IsSent");
                    this.OnIsSentChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class HighRiskOperations : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.Guid _TerminalsGroupId;

        private System.Nullable<System.DateTime> _Date;

        private System.Nullable<int> _UserId;

        private System.Nullable<int> _ShiftId;

        private string _Action;

        private EntityRef<Shifts> _Shifts;

        private EntityRef<Users> _Users;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnTerminalsGroupIdChanging(System.Guid value);
        partial void OnTerminalsGroupIdChanged();
        partial void OnDateChanging(System.Nullable<System.DateTime> value);
        partial void OnDateChanged();
        partial void OnUserIdChanging(System.Nullable<int> value);
        partial void OnUserIdChanged();
        partial void OnShiftIdChanging(System.Nullable<int> value);
        partial void OnShiftIdChanged();
        partial void OnActionChanging(string value);
        partial void OnActionChanged();

        #endregion

        public HighRiskOperations()
        {
            this._Shifts = default(EntityRef<Shifts>);
            this._Users = default(EntityRef<Users>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TerminalsGroupId",
            DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid TerminalsGroupId
        {
            get { return this._TerminalsGroupId; }
            set
            {
                if ((this._TerminalsGroupId != value))
                {
                    this.OnTerminalsGroupIdChanging(value);
                    this.SendPropertyChanging();
                    this._TerminalsGroupId = value;
                    this.SendPropertyChanged("TerminalsGroupId");
                    this.OnTerminalsGroupIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Date", DbType = "DateTime")]
        public System.Nullable<System.DateTime> Date
        {
            get { return this._Date; }
            set
            {
                if ((this._Date != value))
                {
                    this.OnDateChanging(value);
                    this.SendPropertyChanging();
                    this._Date = value;
                    this.SendPropertyChanged("Date");
                    this.OnDateChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserId", DbType = "Int")]
        public System.Nullable<int> UserId
        {
            get { return this._UserId; }
            set
            {
                if ((this._UserId != value))
                {
                    if (this._Users.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnUserIdChanging(value);
                    this.SendPropertyChanging();
                    this._UserId = value;
                    this.SendPropertyChanged("UserId");
                    this.OnUserIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ShiftId", DbType = "Int")]
        public System.Nullable<int> ShiftId
        {
            get { return this._ShiftId; }
            set
            {
                if ((this._ShiftId != value))
                {
                    if (this._Shifts.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnShiftIdChanging(value);
                    this.SendPropertyChanging();
                    this._ShiftId = value;
                    this.SendPropertyChanged("ShiftId");
                    this.OnShiftIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Action", DbType = "NVarChar(30) NOT NULL",
            CanBeNull = false)]
        public string Action
        {
            get { return this._Action; }
            set
            {
                if ((this._Action != value))
                {
                    this.OnActionChanging(value);
                    this.SendPropertyChanging();
                    this._Action = value;
                    this.SendPropertyChanged("Action");
                    this.OnActionChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_HighRiskOperations_ShiftId",
            Storage = "_Shifts", ThisKey = "ShiftId", OtherKey = "Id", IsForeignKey = true)]
        public Shifts Shifts
        {
            get { return this._Shifts.Entity; }
            set
            {
                Shifts previousValue = this._Shifts.Entity;
                if (((previousValue != value)
                     || (this._Shifts.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._Shifts.Entity = null;
                        previousValue.HighRiskOperations.Remove(this);
                    }

                    this._Shifts.Entity = value;
                    if ((value != null))
                    {
                        value.HighRiskOperations.Add(this);
                        this._ShiftId = value.Id;
                    }
                    else
                    {
                        this._ShiftId = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("Shifts");
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_HighRiskOperations_UserId",
            Storage = "_Users", ThisKey = "UserId", OtherKey = "Id", IsForeignKey = true)]
        public Users Users
        {
            get { return this._Users.Entity; }
            set
            {
                Users previousValue = this._Users.Entity;
                if (((previousValue != value)
                     || (this._Users.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._Users.Entity = null;
                        previousValue.HighRiskOperations.Remove(this);
                    }

                    this._Users.Entity = value;
                    if ((value != null))
                    {
                        value.HighRiskOperations.Add(this);
                        this._UserId = value.Id;
                    }
                    else
                    {
                        this._UserId = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("Users");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Messages : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.Guid _Uuid;

        private System.DateTime _DateTime;

        private System.Data.Linq.Binary _Message;

        private bool _IsSent;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnUuidChanging(System.Guid value);
        partial void OnUuidChanged();
        partial void OnDateTimeChanging(System.DateTime value);
        partial void OnDateTimeChanged();
        partial void OnMessageChanging(System.Data.Linq.Binary value);
        partial void OnMessageChanged();
        partial void OnIsSentChanging(bool value);
        partial void OnIsSentChanged();

        #endregion

        public Messages()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Uuid", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid Uuid
        {
            get { return this._Uuid; }
            set
            {
                if ((this._Uuid != value))
                {
                    this.OnUuidChanging(value);
                    this.SendPropertyChanging();
                    this._Uuid = value;
                    this.SendPropertyChanged("Uuid");
                    this.OnUuidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DateTime", DbType = "DateTime NOT NULL")]
        public System.DateTime DateTime
        {
            get { return this._DateTime; }
            set
            {
                if ((this._DateTime != value))
                {
                    this.OnDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._DateTime = value;
                    this.SendPropertyChanged("DateTime");
                    this.OnDateTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Message", DbType = "Image", CanBeNull = true,
            UpdateCheck = UpdateCheck.Never)]
        public System.Data.Linq.Binary Message
        {
            get { return this._Message; }
            set
            {
                if ((this._Message != value))
                {
                    this.OnMessageChanging(value);
                    this.SendPropertyChanging();
                    this._Message = value;
                    this.SendPropertyChanged("Message");
                    this.OnMessageChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsSent", DbType = "Bit NOT NULL")]
        public bool IsSent
        {
            get { return this._IsSent; }
            set
            {
                if ((this._IsSent != value))
                {
                    this.OnIsSentChanging(value);
                    this.SendPropertyChanging();
                    this._IsSent = value;
                    this.SendPropertyChanged("IsSent");
                    this.OnIsSentChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Orders : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.Nullable<int> _Shiftid;

        private System.Guid _OrderId;

        private System.Nullable<System.DateTime> _DateTime;

        private System.Data.Linq.Binary _Data;

        private System.Nullable<int> _Count;

        private bool _Deleted;

        private EntityRef<Shifts> _Shifts;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnShiftidChanging(System.Nullable<int> value);
        partial void OnShiftidChanged();
        partial void OnOrderIdChanging(System.Guid value);
        partial void OnOrderIdChanged();
        partial void OnDateTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnDateTimeChanged();
        partial void OnDataChanging(System.Data.Linq.Binary value);
        partial void OnDataChanged();
        partial void OnCountChanging(System.Nullable<int> value);
        partial void OnCountChanged();
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();

        #endregion

        public Orders()
        {
            this._Shifts = default(EntityRef<Shifts>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Shiftid", DbType = "Int")]
        public System.Nullable<int> Shiftid
        {
            get { return this._Shiftid; }
            set
            {
                if ((this._Shiftid != value))
                {
                    if (this._Shifts.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnShiftidChanging(value);
                    this.SendPropertyChanging();
                    this._Shiftid = value;
                    this.SendPropertyChanged("Shiftid");
                    this.OnShiftidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OrderId", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid OrderId
        {
            get { return this._OrderId; }
            set
            {
                if ((this._OrderId != value))
                {
                    this.OnOrderIdChanging(value);
                    this.SendPropertyChanging();
                    this._OrderId = value;
                    this.SendPropertyChanged("OrderId");
                    this.OnOrderIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DateTime", DbType = "DateTime")]
        public System.Nullable<System.DateTime> DateTime
        {
            get { return this._DateTime; }
            set
            {
                if ((this._DateTime != value))
                {
                    this.OnDateTimeChanging(value);
                    this.SendPropertyChanging();
                    this._DateTime = value;
                    this.SendPropertyChanged("DateTime");
                    this.OnDateTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Data", DbType = "Image", CanBeNull = true,
            UpdateCheck = UpdateCheck.Never)]
        public System.Data.Linq.Binary Data
        {
            get { return this._Data; }
            set
            {
                if ((this._Data != value))
                {
                    this.OnDataChanging(value);
                    this.SendPropertyChanging();
                    this._Data = value;
                    this.SendPropertyChanged("Data");
                    this.OnDataChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Count", DbType = "Int")]
        public System.Nullable<int> Count
        {
            get { return this._Count; }
            set
            {
                if ((this._Count != value))
                {
                    this.OnCountChanging(value);
                    this.SendPropertyChanging();
                    this._Count = value;
                    this.SendPropertyChanged("Count");
                    this.OnCountChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Deleted", DbType = "Bit NOT NULL")]
        public bool Deleted
        {
            get { return this._Deleted; }
            set
            {
                if ((this._Deleted != value))
                {
                    this.OnDeletedChanging(value);
                    this.SendPropertyChanging();
                    this._Deleted = value;
                    this.SendPropertyChanged("Deleted");
                    this.OnDeletedChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Orders_ShiftId", Storage = "_Shifts",
            ThisKey = "Shiftid", OtherKey = "Id", IsForeignKey = true)]
        public Shifts Shifts
        {
            get { return this._Shifts.Entity; }
            set
            {
                Shifts previousValue = this._Shifts.Entity;
                if (((previousValue != value)
                     || (this._Shifts.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._Shifts.Entity = null;
                        previousValue.Orders.Remove(this);
                    }

                    this._Shifts.Entity = value;
                    if ((value != null))
                    {
                        value.Orders.Add(this);
                        this._Shiftid = value.Id;
                    }
                    else
                    {
                        this._Shiftid = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("Shifts");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Shifts : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.DateTime _OpenTime;

        private System.Nullable<System.DateTime> _CloseTime;

        private System.Nullable<int> _OpenerUserId;

        private System.Nullable<int> _CloserUserId;

        private EntitySet<HighRiskOperations> _HighRiskOperations;

        private EntitySet<Orders> _Orders;

        private EntityRef<Users> _Users;

        private EntityRef<Users> _OpenerUser;

        private EntityRef<Users> _CloserUser;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnOpenTimeChanging(System.DateTime value);
        partial void OnOpenTimeChanged();
        partial void OnCloseTimeChanging(System.Nullable<System.DateTime> value);
        partial void OnCloseTimeChanged();
        partial void OnOpenerUserIdChanging(System.Nullable<int> value);
        partial void OnOpenerUserIdChanged();
        partial void OnCloserUserIdChanging(System.Nullable<int> value);
        partial void OnCloserUserIdChanged();

        #endregion

        public Shifts()
        {
            this._HighRiskOperations = new EntitySet<HighRiskOperations>(
                new Action<HighRiskOperations>(this.attach_HighRiskOperations),
                new Action<HighRiskOperations>(this.detach_HighRiskOperations));
            this._Orders = new EntitySet<Orders>(new Action<Orders>(this.attach_Orders),
                new Action<Orders>(this.detach_Orders));
            this._Users = default(EntityRef<Users>);
            this._OpenerUser = default(EntityRef<Users>);
            this._CloserUser = default(EntityRef<Users>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OpenTime", DbType = "DateTime NOT NULL")]
        public System.DateTime OpenTime
        {
            get { return this._OpenTime; }
            set
            {
                if ((this._OpenTime != value))
                {
                    this.OnOpenTimeChanging(value);
                    this.SendPropertyChanging();
                    this._OpenTime = value;
                    this.SendPropertyChanged("OpenTime");
                    this.OnOpenTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CloseTime", DbType = "DateTime")]
        public System.Nullable<System.DateTime> CloseTime
        {
            get { return this._CloseTime; }
            set
            {
                if ((this._CloseTime != value))
                {
                    this.OnCloseTimeChanging(value);
                    this.SendPropertyChanging();
                    this._CloseTime = value;
                    this.SendPropertyChanged("CloseTime");
                    this.OnCloseTimeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_OpenerUserId", DbType = "Int")]
        public System.Nullable<int> OpenerUserId
        {
            get { return this._OpenerUserId; }
            set
            {
                if ((this._OpenerUserId != value))
                {
                    if ((this._Users.HasLoadedOrAssignedValue || this._OpenerUser.HasLoadedOrAssignedValue))
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnOpenerUserIdChanging(value);
                    this.SendPropertyChanging();
                    this._OpenerUserId = value;
                    this.SendPropertyChanged("OpenerUserId");
                    this.OnOpenerUserIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CloserUserId", DbType = "Int")]
        public System.Nullable<int> CloserUserId
        {
            get { return this._CloserUserId; }
            set
            {
                if ((this._CloserUserId != value))
                {
                    if (this._CloserUser.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnCloserUserIdChanging(value);
                    this.SendPropertyChanging();
                    this._CloserUserId = value;
                    this.SendPropertyChanged("CloserUserId");
                    this.OnCloserUserIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_HighRiskOperations_ShiftId",
            Storage = "_HighRiskOperations", ThisKey = "Id", OtherKey = "ShiftId", DeleteRule = "CASCADE")]
        public EntitySet<HighRiskOperations> HighRiskOperations
        {
            get { return this._HighRiskOperations; }
            set { this._HighRiskOperations.Assign(value); }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Orders_ShiftId", Storage = "_Orders",
            ThisKey = "Id", OtherKey = "Shiftid", DeleteRule = "NO ACTION")]
        public EntitySet<Orders> Orders
        {
            get { return this._Orders; }
            set { this._Orders.Assign(value); }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users", Storage = "_Users",
            ThisKey = "OpenerUserId", OtherKey = "Id", IsForeignKey = true)]
        public Users Users
        {
            get { return this._Users.Entity; }
            set
            {
                Users previousValue = this._Users.Entity;
                if (((previousValue != value)
                     || (this._Users.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._Users.Entity = null;
                        previousValue.Shifts.Remove(this);
                    }

                    this._Users.Entity = value;
                    if ((value != null))
                    {
                        value.Shifts.Add(this);
                        this._OpenerUserId = value.Id;
                    }
                    else
                    {
                        this._OpenerUserId = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("Users");
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users1", Storage = "_OpenerUser",
            ThisKey = "OpenerUserId", OtherKey = "Id", IsForeignKey = true)]
        public Users OpenerUser
        {
            get { return this._OpenerUser.Entity; }
            set
            {
                Users previousValue = this._OpenerUser.Entity;
                if (((previousValue != value)
                     || (this._OpenerUser.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._OpenerUser.Entity = null;
                        previousValue.Shifts_Users1.Remove(this);
                    }

                    this._OpenerUser.Entity = value;
                    if ((value != null))
                    {
                        value.Shifts_Users1.Add(this);
                        this._OpenerUserId = value.Id;
                    }
                    else
                    {
                        this._OpenerUserId = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("OpenerUser");
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users2", Storage = "_CloserUser",
            ThisKey = "CloserUserId", OtherKey = "Id", IsForeignKey = true)]
        public Users CloserUser
        {
            get { return this._CloserUser.Entity; }
            set
            {
                Users previousValue = this._CloserUser.Entity;
                if (((previousValue != value)
                     || (this._CloserUser.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._CloserUser.Entity = null;
                        previousValue.Shifts_Users2.Remove(this);
                    }

                    this._CloserUser.Entity = value;
                    if ((value != null))
                    {
                        value.Shifts_Users2.Add(this);
                        this._CloserUserId = value.Id;
                    }
                    else
                    {
                        this._CloserUserId = default(Nullable<int>);
                    }

                    this.SendPropertyChanged("CloserUser");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_HighRiskOperations(HighRiskOperations entity)
        {
            this.SendPropertyChanging();
            entity.Shifts = this;
        }

        private void detach_HighRiskOperations(HighRiskOperations entity)
        {
            this.SendPropertyChanging();
            entity.Shifts = null;
        }

        private void attach_Orders(Orders entity)
        {
            this.SendPropertyChanging();
            entity.Shifts = this;
        }

        private void detach_Orders(Orders entity)
        {
            this.SendPropertyChanging();
            entity.Shifts = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute()]
    public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _Id;

        private System.Guid _UserId;

        private string _UserName;

        private EntitySet<HighRiskOperations> _HighRiskOperations;

        private EntitySet<Shifts> _Shifts;

        private EntitySet<Shifts> _Shifts_Users1;

        private EntitySet<Shifts> _Shifts_Users2;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnUserIdChanging(System.Guid value);
        partial void OnUserIdChanged();
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();

        #endregion

        public Users()
        {
            this._HighRiskOperations = new EntitySet<HighRiskOperations>(
                new Action<HighRiskOperations>(this.attach_HighRiskOperations),
                new Action<HighRiskOperations>(this.detach_HighRiskOperations));
            this._Shifts = new EntitySet<Shifts>(new Action<Shifts>(this.attach_Shifts),
                new Action<Shifts>(this.detach_Shifts));
            this._Shifts_Users1 = new EntitySet<Shifts>(new Action<Shifts>(this.attach_Shifts_Users1),
                new Action<Shifts>(this.detach_Shifts_Users1));
            this._Shifts_Users2 = new EntitySet<Shifts>(new Action<Shifts>(this.attach_Shifts_Users2),
                new Action<Shifts>(this.detach_Shifts_Users2));
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Id", AutoSync = AutoSync.OnInsert,
            DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id
        {
            get { return this._Id; }
            set
            {
                if ((this._Id != value))
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserId", DbType = "UniqueIdentifier NOT NULL")]
        public System.Guid UserId
        {
            get { return this._UserId; }
            set
            {
                if ((this._UserId != value))
                {
                    this.OnUserIdChanging(value);
                    this.SendPropertyChanging();
                    this._UserId = value;
                    this.SendPropertyChanged("UserId");
                    this.OnUserIdChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserName", DbType = "NVarChar(100) NOT NULL",
            CanBeNull = false)]
        public string UserName
        {
            get { return this._UserName; }
            set
            {
                if ((this._UserName != value))
                {
                    this.OnUserNameChanging(value);
                    this.SendPropertyChanging();
                    this._UserName = value;
                    this.SendPropertyChanged("UserName");
                    this.OnUserNameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_HighRiskOperations_UserId",
            Storage = "_HighRiskOperations", ThisKey = "Id", OtherKey = "UserId", DeleteRule = "NO ACTION")]
        public EntitySet<HighRiskOperations> HighRiskOperations
        {
            get { return this._HighRiskOperations; }
            set { this._HighRiskOperations.Assign(value); }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users", Storage = "_Shifts",
            ThisKey = "Id", OtherKey = "OpenerUserId", DeleteRule = "NO ACTION")]
        public EntitySet<Shifts> Shifts
        {
            get { return this._Shifts; }
            set { this._Shifts.Assign(value); }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users1", Storage = "_Shifts_Users1",
            ThisKey = "Id", OtherKey = "OpenerUserId", DeleteRule = "NO ACTION")]
        public EntitySet<Shifts> Shifts_Users1
        {
            get { return this._Shifts_Users1; }
            set { this._Shifts_Users1.Assign(value); }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "FK_Shifts_Users2", Storage = "_Shifts_Users2",
            ThisKey = "Id", OtherKey = "CloserUserId", DeleteRule = "NO ACTION")]
        public EntitySet<Shifts> Shifts_Users2
        {
            get { return this._Shifts_Users2; }
            set { this._Shifts_Users2.Assign(value); }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_HighRiskOperations(HighRiskOperations entity)
        {
            this.SendPropertyChanging();
            entity.Users = this;
        }

        private void detach_HighRiskOperations(HighRiskOperations entity)
        {
            this.SendPropertyChanging();
            entity.Users = null;
        }

        private void attach_Shifts(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.Users = this;
        }

        private void detach_Shifts(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.Users = null;
        }

        private void attach_Shifts_Users1(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.OpenerUser = this;
        }

        private void detach_Shifts_Users1(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.OpenerUser = null;
        }

        private void attach_Shifts_Users2(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.CloserUser = this;
        }

        private void detach_Shifts_Users2(Shifts entity)
        {
            this.SendPropertyChanging();
            entity.CloserUser = null;
        }
    }
}
#pragma warning restore 1591